# ## FAME3 run005
# run:
#   experiment_id: Run005_20230321_FAME3_NAA10_Ilaria
#   ## input_dir: /projects/humgen-seq/MinION_Mk1B.MN37911/device_output/Run005_20230321_FAME3_NAA10_Ilaria/no_sample/20230321_1056_MN37911_FAW44825_2fd0ef84 # humgen-seq
#   input_dir: /local/work/fkilpert/Run005_20230321_FAME3_NAA10_Ilaria/no_sample/20230321_1056_MN37911_FAW44825_2fd0ef84 # ikim g1-7
#   sample_sheet: sample_sheets/Run005_20230321_FAME3_NAA10_Ilaria.sample_sheet.csv
#   barcode_kits:
#     - EXP-NBD196