## run013_20240515_MARCHF6
run:
  experiment_id: run013_20240515_MARCHF6
  input_dir: /home/kilpert/sshfs/projects/humgen-seq/MinION_Mk1B.MN37911/device_output/run013_20240515_MARCHF6
  sample_sheet:
  barcode_kits:
    - EXP-NBD196
  ## Make your choice (guppy is configured with: flowcell+kit OR cfg). cfg will overrule flowcell+kit in this workflow!
  ## flowcell: FLO-MIN106 # starts with "FLO"
  ## library_prep_kit: SQK-LSK109 # starts with "SQK" or "VSK"

