## Run specific settings

## MinKNOW fast5 dir (searching *recursively* for all fast5 files!)
## specify path to MinKnow output dir (e.g. 20220412_1232_MN37911_FAR54812_bfd8a256 of format: run_date run_time position flow_cell_id run_id_shorthash)


## FAME3 run1
# run:
  # input_dir: /vol/minion/minknow/data/001_20220412_FAME3/no_sample/20220412_1232_MN37911_FAR54812_bfd8a256
  # sample_sheet: sample_sheets/001_20220412_FAME3.sample_sheet.csv
  # ##sample_sheet: sample_sheets/example.sample_sheet.csv
  # barcode_kits:
    # - EXP-NBD196
  # ## Make your choice (guppy is configured with: flowcell+kit OR cfg). cfg will overrule flowcell+kit in this workflow!
  # ## flowcell: FLO-MIN106 # starts with "FLO"
  # ## library_prep_kit: SQK-LSK109 # starts with "SQK" or "VSK"
  # ## OR:


## FAME3 run2
run:
  input_dir: /vol/minion/minknow/data/004_20221019_FAME3_DAB1_FGF14_SCA8/no_sample/20221019_1314_MN37911_FAR58791_d2fc7041
  sample_sheet: sample_sheets/004_20221019_FAME3_DAB1_FGF14_SCA8.sample_sheet.csv
  ##sample_sheet: sample_sheets/example.sample_sheet.csv
  barcode_kits:
    - EXP-NBD196
  ## Make your choice (guppy is configured with: flowcell+kit OR cfg). cfg will overrule flowcell+kit in this workflow!
  ## flowcell: FLO-MIN106 # starts with "FLO"
  ## library_prep_kit: SQK-LSK109 # starts with "SQK" or "VSK"
  ## OR:


## Internal settings (DO NOT CHANGE!!!) ################################################################################

## Output dir
# outdir: results # default: 'results'


## Guppy
guppy_cfg: # fast or hac or sup; <strand type>_<pore version>_<speed>_<custom tags>.cfg
  - dna_r9.4.1_450bps_fast.cfg
  - dna_r9.4.1_450bps_hac.cfg
  - dna_r9.4.1_450bps_sup.cfg


guppy_basecaller:
  ## bin: /vol/minion/opt/ont-guppy_6.1.5/bin/guppy_basecaller
  ## bin: /vol/minion/opt/ont-guppy_6.2.1/bin/guppy_basecaller
  ## bin: /vol/minion/opt/ont-guppy_6.3.4/bin/guppy_basecaller
  ont-guppy_6.3.7:
    bin: /vol/minion/opt/ont-guppy_6.3.7/bin/guppy_basecaller # remove --trim_barcodes (on by default)
    parameter: -x auto --disable_pings --recursive --compress_fastq --do_read_splitting --calib_detect --records_per_fastq 0 # --trim_barcodes # --nested_output_folder
  ont-guppy_6.3.8:
    bin: /vol/minion/opt/ont-guppy_6.3.8/bin/guppy_basecaller # remove --trim_barcodes (on by default)
    parameter: -x auto --disable_pings --recursive --compress_fastq --do_read_splitting --calib_detect --records_per_fastq 0 # --trim_barcodes # --nested_output_folder

