## FAME3 run011
run:
  experiment_id: run011_20230921_FGF14_FAME_NAA10
  input_dir: /vol/minion/minknow_backup/data/run011_20230921_FGF14_FAME_NAA10/no_sample/20230921_0913_MN37911_FAW86931_874371bb # minion.local
  sample_sheet: sample_sheets/run011.sample_sheet.csv
  barcode_kits:
    - EXP-NBD196


outdir: results.FAME3-2


gpu_requests: 1

