## run011_20230921_FGF14_FAME_NAA10

run:
  experiment_id: run011
  input_dir: /vol/minion/minknow_backup/data/run011_20230921_FGF14_FAME_NAA10/no_sample/20230921_0913_MN37911_FAW86931_874371bb # minion.local
  sample_sheet: sample_sheets/run011.sample_sheet.csv
  barcode_kits:
    - EXP-NBD196
  ## Make your choice (guppy is configured with: flowcell+kit OR cfg). cfg will overrule flowcell+kit in this workflow!
  ## flowcell: FLO-MIN106 # starts with "FLO"
  ## library_prep_kit: SQK-LSK109 # starts with "SQK" or "VSK"
  

outdir: results.FAME3-2


gpu_requests: 1

