## run16_20251001_MARCHF6_FGF14_RNU2s

run:
  experiment_id: run016
  input_dir: /vol/minion/minknow_backup/data/run16_20251001_MARCHF6_FGF14_RNU2s/no_sample_id/20251001_1008_MN37911_FAZ40399_8ee791b2 # minion.local
  sample_sheet: sample_sheets/run016.sample_sheet.csv
  barcode_kits:
    - SQK-NBD114-96
  ## Make your choice (guppy is configured with: flowcell+kit OR cfg). cfg will overrule flowcell+kit in this workflow!
  ## flowcell: FLO-MIN106 # starts with "FLO"
  ## library_prep_kit: SQK-LSK109 # starts with "SQK" or "VSK"


outdir: results.no-trim/2025-10-02


gpu_requests: 1

