## run013_20240515_MARCHF6

run:
  experiment_id: run013
  input_dir: /vol/minion/minknow_backup/data/run013_20240515_MARCHF6/no_sample/20240515_0944_MN37911_FAY01820_b8e1ac8d # minion.local
  sample_sheet: sample_sheets/run013.sample_sheet.csv
  barcode_kits:
    - EXP-NBD196
  ## Make your choice (guppy is configured with: flowcell+kit OR cfg). cfg will overrule flowcell+kit in this workflow!
  ## flowcell: FLO-MIN106 # starts with "FLO"
  ## library_prep_kit: SQK-LSK109 # starts with "SQK" or "VSK"
  

outdir: results/2024-12-18


gpu_requests: 1

